FROM python:3.12-slim AS base

WORKDIR /home

RUN apt-get -yqq update && \
    apt-get install -yq --no-install-recommends curl binutils xz-utils ca-certificates expat libgomp1 && \
    apt-get autoremove -y && \
    apt-get clean -y

FROM base as ffmpeg
RUN apt-get install -y curl binutils xz-utils
RUN curl -L -o emby.deb https://github.com/MediaBrowser/Emby.Releases/releases/download/4.8.10.0/emby-server-deb_4.8.10.0_amd64.deb
RUN ar x emby.deb data.tar.xz && \
    tar xf data.tar.xz

FROM base AS final

WORKDIR /home

RUN apt-get install -y libfontconfig

COPY requirements* ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-dev.txt
COPY *.py ./

COPY --from=ffmpeg /home/opt/emby-server/bin/ffmpeg /usr/bin/ffmpeg
COPY --from=ffmpeg /home/opt/emby-server/lib/libav*.so.* /usr/lib/
COPY --from=ffmpeg /home/opt/emby-server/lib/libpostproc.so.* /usr/lib/
COPY --from=ffmpeg /home/opt/emby-server/lib/libsw* /usr/lib/
COPY --from=ffmpeg /home/opt/emby-server/extra/lib/libva*.so.* /usr/lib/
COPY --from=ffmpeg /home/opt/emby-server/extra/lib/libdrm.so.* /usr/lib/
COPY --from=ffmpeg /home/opt/emby-server/extra/lib/libmfx.so.* /usr/lib/
COPY --from=ffmpeg /home/opt/emby-server/extra/lib/libOpenCL.so.* /usr/lib/

